eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka
    region: defaultZone
spring:    
  application:
    name: MyStupidService
     
logging:
  level:
    com.oreilly.cloud: INFO
    