eureka:
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka,http://peer1:8761/eureka
    region: defaultZone
spring:    
  application:
    name: SoVeryHappy
     
logging:
  level:
    com.oreilly.cloud: INFO
    