eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/
spring:    
  application:
    name: MyStupidService
     
logging:
  level:
    com.example.howtodoinjava: DEBUG
    