server:
  port: 8762
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: 
      defaultZone: http://peer1:8761
  instance:
    hostname: peer2
    health-check-url: http://peer2:8762/health
    status-page-url: http://peer2:8762/status
  